version: '3.8'

services:
  user-service-db:
    image: postgres:15
    container_name: user-service-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5000:5432"     # <-- If you want to connect to DB from host, else remove this line to hide it
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - swens

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    depends_on:
      - user-service-db
    # NO ports mapping here - not exposed outside
    environment:
      SERVER_PORT: 4000
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      GRPC_SERVER_PORT: 9090
    networks:
      - swens

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    depends_on:
      - user-service
    # NO ports mapping here - not exposed outside
    environment:
      SERVER_PORT: 3000
      GRPC_CLIENT_USERSERVICE_ADDRESS: static://user-service:9090
      JWT_SECRET: vLw4a7v7D1XqXx+MshFwPVmIb7A3DCw2r+VtGMLglWc=
    networks:
      - swens

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"    # <-- Only API Gateway exposed externally
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - auth-service
      - user-service
    networks:
      - swens

volumes:
  pgdata:

networks:
  swens:
    external: true
