version: '3.8'

services:
  user-service-db:
    image: postgres:15
    container_name: user-service-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: password
    ports:
      - "5000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - swens

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    depends_on:
      - user-service-db
    ports:
      - "4000:4000"
      - "9090:9090"  # gRPC port
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-service-db:5432/db
      SPRING_DATASOURCE_USERNAME: admin_user
      SPRING_DATASOURCE_PASSWORD: password
      GRPC_SERVER_PORT: 9090
    networks:
      - swens

  auth-service:
    build:
      context: ./auth-service
    container_name: auth-service
    ports:
      - "3000:3000"
    environment:
      SERVER_PORT: 3000
      GRPC_CLIENT_USERSERVICE_ADDRESS: static://user-service:9090
      JWT_SECRET: vLw4a7v7D1XqXx+MshFwPVmIb7A3DCw2r+VtGMLglWc=
    depends_on:
      - user-service
    networks:
      - swens

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - auth-service
      - user-service
    networks:
      - swens

volumes:
  pgdata:

networks:
  swens:
    external: true
