server:
  port: 8080  # API Gateway port

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:3000
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: http://user-service:4000
          predicates:
            - Path=/users/**

      default-filters:
        - name: JwtValidation

auth:
  service:
    url: http://auth-service:3000
