server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - PreserveHostHeader
      routes:
        - id: auth-service
          uri: http://auth-service:3000
          predicates:
            - Path=/auth/**

        - id: user-service
          uri: http://user-service:4000
          predicates:
            - Path=/users/**

        - id: task-service
          uri: http://task-service:6000
          predicates:
            - Path=/task/**
          filters:
            - name: JwtValidation
            - name: RoleFilter
              args:
                requiredRole: ADMIN

auth:
  service:
    url: http://auth-service:3000
